//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_TIPO_CP
    {
        public decimal ID_TIPO_CP { get; set; }
        public string NOM_TIPO_CP { get; set; }
        public string ABR_TIPO_CP { get; set; }
        public decimal ID_USUARIO_ACTUALIZACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
    }
}
