
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NSPecor.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
public partial class MUB_TENSION
{
    [Key]
    public short ID_TENSION { get; set; }
    public Nullable<short> ID_NIVEL_TENSION { get; set; }
    [DisplayName("DESCRIPCIÓN")]
    [Required]
    public string DESCRIPCION { get; set; }



    public virtual MUB_NIVEL_TENSION MUB_NIVEL_TENSION { get; set; }

}

}
