
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NSPecor.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MUH_PECOR_COBERTURA
{

    public string DPTO_CCDGO { get; set; }

    public string MPIO_CCDGO { get; set; }

    public string VIGENCIA_ANT { get; set; }

    public Nullable<decimal> VSS_BENEFIADAS { get; set; }

    public decimal ID_PLAN { get; set; }

    public Nullable<decimal> ICEE { get; set; }

    public Nullable<decimal> V_TOTAL { get; set; }

    public Nullable<decimal> VSS_TOTAL { get; set; }

    public Nullable<decimal> NBI { get; set; }

    public Nullable<decimal> ICEE_VIVTOT { get; set; }

    public Nullable<decimal> ICEE_VSS_TOT { get; set; }

    public Nullable<decimal> CU_DIESEL { get; set; }

    public string DPTO_NOMBRE { get; set; }

    public string MPIO_NOMBRE { get; set; }



    public virtual MUB_PECOR_PLAN MUB_PECOR_PLAN { get; set; }

}

}
